### ISSUE TITLE
Multi GPU training

### ISSUE THREAD

**Issue by Pawankhatri2k13** [dhgrs/chainer-WaveGlow#2]
How to train for multiple GPUs ?

**Comment by Pawankhatri2k13** [comment]
Ok, as per code I used following command for multiGpu training,
>>> python train.py --gpus 0 1 2 3 4 5 6 7
but it gives following error,

GPUs: 0
# train: 1850
# valid: 206
# Minibatch-size: 2
# iteration: 500000

Exception in main training loop: batch is empty
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/chainer/training/trainer.py", line 315, in run
    update()
  File "/usr/local/lib/python3.5/dist-packages/chainer/training/updaters/standard_updater.py", line 165, in update
    self.update_core()
  File "/usr/local/lib/python3.5/dist-packages/chainer/training/updaters/parallel_updater.py", line 119, in update_core
    batch[i::n], self._devices[key])
  File "/usr/local/lib/python3.5/dist-packages/chainer/dataset/convert.py", line 123, in concat_examples
    raise ValueError('batch is empty')
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "train.py", line 143, in <module>
    trainer.run()
  File "/usr/local/lib/python3.5/dist-packages/chainer/training/trainer.py", line 329, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/chainer/training/trainer.py", line 315, in run
    update()
  File "/usr/local/lib/python3.5/dist-packages/chainer/training/updaters/standard_updater.py", line 165, in update
    self.update_core()
  File "/usr/local/lib/python3.5/dist-packages/chainer/training/updaters/parallel_updater.py", line 119, in update_core
    batch[i::n], self._devices[key])
  File "/usr/local/lib/python3.5/dist-packages/chainer/dataset/convert.py", line 123, in concat_examples
    raise ValueError('batch is empty')
ValueError: batch is empty



Any idea what's the problem ?

**Comment by dhgrs** [comment]
`batchsize` in `params.py` means total batch size across all GPUs. So if you want to train batch size per GPU = 2 with 8 GPUs, please set `batchsize` 16.

And sorry that I have only single GPU so I didn't check whether this program run or not. If it doesn't work, please report on this issue.

**Comment by Pawankhatri2k13** [comment]
Yes, by setting **batchsize** = **16**.
Training on 8 GPUs has started.

Thanks.

**Comment by deepconsc** [comment]
@Pawankhatri2k13  any results?
