### ISSUE TITLE
Training on different dataset on multiple gpus throws error 

### ISSUE THREAD

**Issue by deepconsc** [dhgrs/chainer-WaveGlow#4]
By executing command `python train.py -g 7 -r snapshot_iter_500000` it throws error you see below. 
P.S. additionally, -g 7 runs the model on eighth gpu, how can I run it on all gpus?

@dhgrs 

```
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    chainer.serializers.load_npz(args.resume, trainer)
  File "/home/lchkhetianni/.conda/envs/TARS/lib/python3.6/site-packages/chainer/serializers/npz.py", line 190, in load_npz
    d.load(obj)
  File "/home/lchkhetianni/.conda/envs/TARS/lib/python3.6/site-packages/chainer/serializer.py", line 83, in load
    obj.serialize(self)
  File "/home/lchkhetianni/.conda/envs/TARS/lib/python3.6/site-packages/chainer/training/trainer.py", line 341, in serialize
    self.updater.serialize(serializer['updater'])
  File "/home/lchkhetianni/.conda/envs/TARS/lib/python3.6/site-packages/chainer/training/updaters/standard_updater.py", line 189, in serialize
    iterator.serialize(serializer['iterator:' + name])
  File "/home/lchkhetianni/.conda/envs/TARS/lib/python3.6/site-packages/chainer/iterators/multiprocess_iterator.py", line 216, in serialize
    serializer('order', self._order)
  File "/home/lchkhetianni/.conda/envs/TARS/lib/python3.6/site-packages/chainer/serializers/npz.py", line 150, in __call__
    numpy.copyto(value, dataset)
ValueError: could not broadcast input array from shape (11790) into shape (0)
Exception ignored in: <bound method MultiprocessIterator.__del__ of <chainer.iterators.multiprocess_iterator.MultiprocessIterator object at 0x7f5f708567b8>>
Traceback (most recent call last):
  File "/home/lchkhetianni/.conda/envs/TARS/lib/python3.6/site-packages/chainer/iterators/multiprocess_iterator.py", line 168, in __del__
  File "/home/lchkhetianni/.conda/envs/TARS/lib/python3.6/site-packages/chainer/iterators/multiprocess_iterator.py", line 321, in terminate
  File "/home/lchkhetianni/.conda/envs/TARS/lib/python3.6/threading.py", line 347, in notify
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method MultiprocessIterator.__del__ of <chainer.iterators.multiprocess_iterator.MultiprocessIterator object at 0x7f5f6d4ca9e8>>
Traceback (most recent call last):
  File "/home/lchkhetianni/.conda/envs/TARS/lib/python3.6/site-packages/chainer/iterators/multiprocess_iterator.py", line 168, in __del__
  File "/home/lchkhetianni/.conda/envs/TARS/lib/python3.6/site-packages/chainer/iterators/multiprocess_iterator.py", line 321, in terminate
  File "/home/lchkhetianni/.conda/envs/TARS/lib/python3.6/threading.py", line 347, in notify
TypeError: 'NoneType' object is not callable
```

**Comment by dhgrs** [comment]
Please try ```python3 train.py -g 0 1 2 3 4 5 6 7 -r snapshot_iter_50000```.
