### ISSUE TITLE
ValueError: could not broadcast input array from shape (11790) into shape (4064)

### ISSUE THREAD

**Issue by deepconsc** [dhgrs/chainer-WaveGlow#5]
Training throws this error. @dhgrs could you please help me out?

```
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    chainer.serializers.load_npz(args.resume, trainer)
  File "/home/lchkhetianni/.local/lib/python3.5/site-packages/chainer/serializers/npz.py", line 221, in load_npz
    d.load(obj)
  File "/home/lchkhetianni/.local/lib/python3.5/site-packages/chainer/serializer.py", line 83, in load
    obj.serialize(self)
  File "/home/lchkhetianni/.local/lib/python3.5/site-packages/chainer/training/trainer.py", line 361, in serialize
    self.updater.serialize(serializer['updater'])
  File "/home/lchkhetianni/.local/lib/python3.5/site-packages/chainer/training/updaters/standard_updater.py", line 194, in serialize
    iterator.serialize(serializer['iterator:' + name])
  File "/home/lchkhetianni/.local/lib/python3.5/site-packages/chainer/iterators/multiprocess_iterator.py", line 221, in serialize
    serializer('order', order)
  File "/home/lchkhetianni/.local/lib/python3.5/site-packages/chainer/serializers/npz.py", line 172, in __call__
    numpy.copyto(value, dataset)
ValueError: could not broadcast input array from shape (11790) into shape (4064)
```

**Comment by dhgrs** [comment]
Chainer's snapshot includes not only network but also iterator(iterations, shuffled oder and etc.). So that snapshot saved with LJSpeech iterator can not be used with other datasets.
Please try this if you want to use pretrained model snapshot with other datasets.
from:
```
chainer.serializers.load_npz(args.resume, trainer)
```

to:
```
chainer.serializers.load_npz(args.resume, model, 'updater/model:main/')
chainer.serializers.load_npz(args.resume, optimizer, 'updater/optimizer:main/')
```
This code load only network and optimizer and does not load iterator.
