### ISSUE TITLE
Exception in main training loop: Argument 'x' has incorrect type

### ISSUE THREAD

**Issue by deepconsc** [dhgrs/chainer-WaveGlow#6]
Installed all required dependencies, and training throws this error:

```
Exception in main training loop: Argument 'x' has incorrect type (expected cupy.core.core.ndarray, got Variable)
Traceback (most recent call last):
  File "/home/lchkhetianni/.local/lib/python3.5/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/home/lchkhetianni/.local/lib/python3.5/site-packages/chainer/training/updaters/standard_updater.py", line 170, in update
    self.update_core()
  File "/home/lchkhetianni/.local/lib/python3.5/site-packages/chainer/training/updaters/parallel_updater.py", line 135, in update_core
    loss = loss_func(*in_arrays)
  File "/home/lchkhetianni/chainer-WaveGlow/WaveGlow/model.py", line 53, in __call__
    z, gaussian_nll, sum_log_s, sum_log_det_W = self._forward(x, condition)
  File "/home/lchkhetianni/chainer-WaveGlow/WaveGlow/model.py", line 81, in _forward
    mean=self.xp.zeros_like(z, dtype=self.xp.float32),
  File "/home/lchkhetianni/.conda/envs/chainer/lib/python3.5/site-packages/cupy/creation/basic.py", line 205, in zeros_like
    order, strides, memptr = _new_like_order_and_strides(a, dtype, order)
  File "/home/lchkhetianni/.conda/envs/chainer/lib/python3.5/site-packages/cupy/creation/basic.py", line 35, in _new_like_order_and_strides
    order = chr(_update_order_char(a, ord(order)))
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "train.py", line 144, in <module>
    trainer.run()
  File "/home/lchkhetianni/.local/lib/python3.5/site-packages/chainer/training/trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "/home/lchkhetianni/.conda/envs/chainer/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/lchkhetianni/.local/lib/python3.5/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/home/lchkhetianni/.local/lib/python3.5/site-packages/chainer/training/updaters/standard_updater.py", line 170, in update
    self.update_core()
  File "/home/lchkhetianni/.local/lib/python3.5/site-packages/chainer/training/updaters/parallel_updater.py", line 135, in update_core
    loss = loss_func(*in_arrays)
  File "/home/lchkhetianni/chainer-WaveGlow/WaveGlow/model.py", line 53, in __call__
    z, gaussian_nll, sum_log_s, sum_log_det_W = self._forward(x, condition)
  File "/home/lchkhetianni/chainer-WaveGlow/WaveGlow/model.py", line 81, in _forward
    mean=self.xp.zeros_like(z, dtype=self.xp.float32),
  File "/home/lchkhetianni/.conda/envs/chainer/lib/python3.5/site-packages/cupy/creation/basic.py", line 205, in zeros_like
    order, strides, memptr = _new_like_order_and_strides(a, dtype, order)
  File "/home/lchkhetianni/.conda/envs/chainer/lib/python3.5/site-packages/cupy/creation/basic.py", line 35, in _new_like_order_and_strides
    order = chr(_update_order_char(a, ord(order)))
TypeError: Argument 'x' has incorrect type (expected cupy.core.core.ndarray, got Variable)
```

**Comment by dhgrs** [comment]
Hmm, I don't know why it cause an error. Could you show the result of ```pip3 list```? I want to know the version of cupy.

Please try to replace `self.xp.*s_like(z, dtype=self.xp.float32)` with `self.xp.*s_like(z.array, dtype=self.xp.float32)` for now.
